url: "https://marmoi.github.io/" 
baseurl: "" # the subpath of your site, e.g. /blog

title: Irene Martín Morató

description: A bit about myself and my research

avatar: "/img/og_irene.png"

theme: jekyll-theme-minimal


author:
    name: Irene Martín Morató
    email: "irene.martinmorato[at]tuni.fi"
    github: marmoi
    og_image: "/img/og_irene.png"
    
footer-links-active:
    email: true
    github: true
    linkedin: true
    
# prose.io config
prose:
  rooturl: '_posts'
  media: 'img'
  ignore:
    - 404.html
    - LICENSE
    - feed.xml
    - _config.yml
    - /_layouts
    - /_includes
    - /css
    - /img
    - /js