url: "https://marmoi.github.io/" 
baseurl: "" # the subpath of your site, e.g. /blog

title: Irene Martín Morató

description: A bit about myself and my research

avatar: "/img/og_irene.png"

theme: jekyll-theme-minimal

# List of links in the navigation bar
navbar-links:
    Publications: "publications"

author:
    name: Irene Martín Morató
    email: "irene.martinmorato[at]tuni.fi"
    github: marmoi
    og_image: "/img/og_irene.png"
    linkedin: in/imartinmorato
    googlescholar: citations?user=w-RbINwAAAAJ&hl=es
    
footer-links-active:
    email: true
    github: true
    linkedin: true
    googlescholar: true

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: false  # add comments to all blog posts
  -
    scope:
      path: "" # all files
    values:
      layout: "default"
      show-avatar: true
    
# prose.io config
prose:
  rooturl: '_posts'
  media: 'img'
  ignore:
    - 404.html
    - LICENSE
    - feed.xml
    - _config.yml
    - /_layouts
    - /_includes
    - /css
    - /img
    - /js